# ------------------------------------------------------------------------------
# File: ruff.toml
# Info: Ruff configuration file
# Author: Adam Brauns (@AdamBrauns)
# ------------------------------------------------------------------------------

[format]
# Format code embedded in docstrings (default: false)
docstring-code-format = true

[lint]
# In addition to the default rules, enable:
#   1) flake8-bugbear (B)
#   2) flake8-comprehensions (C4)
#   3) flake8-simplify (SIM)
#   4) flynt (FLY)
#   5) isort (I)
#   6) pyupgrade (UP)
extend-select = ["B", "C4", "SIM", "FLY", "I", "UP"]
