# ------------------------------------------------------------------------------
# File: .bash_aliases
# Info: User defined bash aliases
# Author: Adam Brauns (@AdamBrauns)
# shellcheck shell=bash
# ------------------------------------------------------------------------------

# General
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ll='ls -l'
alias la='ll -a'
alias grep='grep --color=auto'
alias erep='grep -E --color=auto'
alias now='date +"%T"'
alias reload='source ~/.bash_profile'
alias skurt='exit'
alias tm='tmux'
alias yeet='rm'

# Rename files by replacing spaces/underscores with dashes and converting to lowercase
alias rndir='rename "s/[ _]/-/g; y/A-Z/a-z/" * -f'

# Format shell scripts with consistent style (2 spaces, indent case/esac, binary operators on separate lines)
# https://google.github.io/styleguide/shellguide.html
alias shfmt='shfmt -w -i 2 -ci -bn'

# Cross-platform port listing
if netstat -tulanp &>/dev/null; then
  alias ports='netstat -tulanp'
else
  alias ports='netstat -an | grep LISTEN'
fi

# Detect OS for ls colors
if ls --color=auto &>/dev/null; then
  alias ls='ls --color=auto'
else
  alias ls='ls -G'
fi

# Change Directory
alias cddot='cd ${DIR_GIT_DOT}'
alias cdgit='cd ${DIR_GIT}'
alias cdmono='cd ${DIR_GIT_MONO}'
alias cdpers='cd ${DIR_GIT_PERSONAL}'
alias cdwork='cd ${DIR_GIT_WORK}'

# Ansible
alias ansdecrypt='ansible-vault decrypt'
alias ansencrypt='ansible-vault encrypt'

# Brew
if command -v brew &> /dev/null; then
  alias brewup='brew update && brew upgrade'
  alias brewall='brew update && brew upgrade --greedy'
  alias brewdump='brew bundle dump -f --file="${DIR_GIT_DOT}/homebrew/Brewfile"'
  alias brewclean='brew autoremove && brew cleanup'
fi

# Claude
if command -v claude &> /dev/null; then
  alias cl='claude'
fi

# Codex
if command -v codex &> /dev/null; then
  alias cx='codex'
fi

# Container
if command -v container &> /dev/null; then
  alias cnt='container'
fi

# Colima
if command -v colima &> /dev/null; then
  alias cod='colima start --kubernetes=false'
  alias cok='colima start --kubernetes'
  alias cos='colima stop'
  alias costatus='colima status'
fi

# Docker
if command -v docker &> /dev/null; then
  alias dk='docker'
  alias dkc='docker compose'
  alias dkps='docker ps'
  alias dkpa='docker ps -a'
  alias dki='docker images'
  alias dkex='docker exec -it'
  alias dklog='docker logs -f'
  alias dkrm='docker rm'
  alias dkrmi='docker rmi'
  alias dkclean='docker system prune -a'
  alias dkcleanf='docker system prune -af'
  alias dkvolclean='docker volume prune'
  alias dknetclean='docker network prune'
  alias dkstartall='docker ps -aq -f status=exited | xargs -r docker start'
  alias dkstopall='docker ps -q | xargs -r docker stop'
  alias dkrmall='docker ps -aq -f status=exited -f status=created | xargs -r docker rm'
  alias dknuke='docker ps -aq | xargs -r docker rm -f'
fi

# Kubernetes
if command -v kubectl &> /dev/null; then
  alias k='kubectl'
  source <(kubectl completion bash)
  complete -o default -F __start_kubectl k
fi

# UV (Python tools)
if command -v uv &> /dev/null; then
  alias uvup='uv tool upgrade --all'
  alias uvinstall='grep -vE "^\s*(#|$)" ~/.config/uv/tools.txt | xargs -I{} uv tool install {}'
  alias uvall='uvinstall && uvup'
  alias uvdump='uv tool list 2>/dev/null | grep -v "^-" | awk "{print \$1}" | sort > ~/.config/uv/tools.txt'
  alias uvclean='uv cache clean'
fi

# SSH
alias sshpi='ssh ${HOST_PI}'
alias sshprox='ssh ${HOST_PROX}'
