# ------------------------------------------------------------------------------
# File: .bash_profile
# Info: Bash profile for user login
# Author: Adam Brauns (@AdamBrauns)
# shellcheck shell=bash
# ------------------------------------------------------------------------------

# Bail out if not running under bash
if [[ -z $BASH_VERSION ]]; then
  return
fi

# Get the aliases and functions
if [[ -f ~/.bashrc ]]; then
  . ~/.bashrc
fi
